apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-all
  namespace: default
  labels:
    strimzi.io/cluster: scenarios-kafka
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
  resources:
    requests:
      cpu: "250m"
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: scenarios-kafka
  namespace: default
  annotations:
    strimzi.io/node-pools: "enabled"
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    jvmOptions:
      "-Xms": "512m"
      "-Xmx": "512m"
  entityOperator:
    topicOperator: {}
    userOperator: {}