apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  namespace: default
  labels:
    strimzi.io/cluster: scenarios-kafka
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafka-user-password
          key: password
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations: ["Read","Write","Describe"]
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations: ["Read"]